package com.example.pzzz.Data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.pzzz.Data.Model.postModel;
import com.example.pzzz.Data.Model.Producto;

import com.example.pzzz.Data.dao.postModelDao;
import com.example.pzzz.Data.dao.ProductoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig postModelDaoConfig;
    private final DaoConfig productoDaoConfig;

    private final postModelDao postModelDao;
    private final ProductoDao productoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        postModelDaoConfig = daoConfigMap.get(postModelDao.class).clone();
        postModelDaoConfig.initIdentityScope(type);

        productoDaoConfig = daoConfigMap.get(ProductoDao.class).clone();
        productoDaoConfig.initIdentityScope(type);

        postModelDao = new postModelDao(postModelDaoConfig, this);
        productoDao = new ProductoDao(productoDaoConfig, this);

        registerDao(postModel.class, postModelDao);
        registerDao(Producto.class, productoDao);
    }
    
    public void clear() {
        postModelDaoConfig.clearIdentityScope();
        productoDaoConfig.clearIdentityScope();
    }

    public postModelDao getPostModelDao() {
        return postModelDao;
    }

    public ProductoDao getProductoDao() {
        return productoDao;
    }

}
